### ISSUE TITLE
Aborting scan with 4 ^C

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/Bug-Reports#114]
Assuming now that ^C^C^C makes a pause at next checkpoint, that ^C^C^C^C will abort the scan.  Got this printout - did not abort cleanly.

```
In [210]: RE(ct(num=1800,delay=2))
Transient Scan ID: 64607
Persistent Unique Scan ID: 'b972415d-7198-4338-84b7-b80a3225c3ed'
+-----------+------------+------------+------------+------------+------------+------------+------------+------------+------------+---------------+
|   seq_num |       time |   sclr_ch2 |   epu1_gap |   epu2_gap | mono_tempa | mono_tempb |  grt1_temp |  grt2_temp |  ring_curr | diag6_monitor |
+-----------+------------+------------+------------+------------+------------+------------+------------+------------+------------+---------------+
|         1 | 11:28:20.6 |       4624 |    57.1840 |    30.8355 |    302.754 |    302.750 |       31.4 |       28.6 |     199.75 |     177898557 |
|         2 | 11:28:24.1 |       4610 |    57.1840 |    30.8355 |    302.754 |    302.752 |       31.6 |       28.7 |     199.75 |     176485203 |
|         3 | 11:28:27.7 |       4616 |    57.1840 |    30.8355 |    302.753 |    302.751 |       31.4 |       28.7 |     199.75 |     177054705 |
|         4 | 11:28:31.2 |       4612 |    57.1840 |    30.8355 |    302.752 |    302.752 |       31.4 |       28.6 |     199.69 |     176228190 |
|         5 | 11:28:34.7 |       4619 |    57.1840 |    30.8355 |    302.751 |    302.754 |       31.4 |       28.7 |     199.69 |     177529023 |
|         6 | 11:28:38.3 |       4621 |    57.1840 |    30.8355 |    302.753 |    302.753 |       31.4 |       28.7 |     199.63 |     177957256 |
|         7 | 11:28:41.9 |       4612 |    57.1840 |    30.8355 |    302.753 |    302.752 |       31.5 |       28.6 |     199.63 |     176966899 |
|         8 | 11:28:45.5 |       4600 |    57.1840 |    30.8355 |    302.753 |    302.754 |       31.4 |       28.7 |     199.63 |     176676989 |
|         9 | 11:28:49.2 |       4591 |    57.1840 |    30.8355 |    302.753 |    302.756 |       31.4 |       28.7 |     199.57 |     177566139 |
|        10 | 11:28:52.8 |       4610 |    57.1840 |    30.8355 |    302.753 |    302.755 |       31.4 |       28.6 |     199.57 |     177829971 |
|        11 | 11:28:56.4 |       4602 |    57.1840 |    30.8355 |    302.752 |    302.750 |       31.4 |       28.7 |     199.51 |     175941839 |
|        12 | 11:29:00.0 |       4596 |    57.1840 |    30.8355 |    302.751 |    302.752 |       31.4 |       28.7 |     199.51 |     177662621 |
|        13 | 11:29:03.6 |       4604 |    57.1840 |    30.8355 |    302.751 |    302.750 |       31.4 |       28.7 |     199.45 |     175583165 |
^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
^C^CAborting....
+-----------+------------+------------+------------+------------+------------+------------+------------+------------+------------+---------------+
generator ct ['b97241'] (scan num: 64607)
Out[210]: ['b972415d-7198-4338-84b7-b80a3225c3ed']

In [211]: Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/IPython/lib/inputhookqt4.py", line 90, in inputhook_qt4
    try:
KeyboardInterrupt

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True



```

**Comment by tacaswell** [comment]
How reproducible is this?  It _looks_ like the can had already aborted and returned by the time you hit the last ^C which somehow ended up getting raised inside of the inputhook method that IPython installed.

**Comment by danielballan** [comment]
Right, that one was more ^C than you should have needed. One to pause at next checkpoint, two to pause ASAP, three to abort. See docs.

**Comment by ambarb** [comment]
Yes, I was tired. It was not 4^C -  I miss counted.

**Comment by danielballan** [comment]
OK, no worries. Closing this issue then.
