### ISSUE TITLE
Exceptions generated at start of scan - not sure what this is doing.

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/Bug-Reports#120]
Reproduced exceptions.  Happened atleast 2 other times after `^C`.  Didn't pay attention to see if it was every time.

```
|         5 | 22:36:16.2 |       1.200 |       1.200 |              11595307 |    302.747 |    302.745 |       31.5 |       28.7 |      84.91 |
|         6 | 22:36:23.8 |       1.275 |       1.275 |              11593014 |    302.744 |    302.741 |       31.6 |       28.7 |      84.90 |
^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
|         7 | 22:36:31.2 |       1.350 |       1.350 |              11591761 |    302.744 |    302.746 |       31.6 |       28.7 |      84.89 |
Pausing...
Out[74]: ['51200ba7-fde6-4a3e-ac60-6658a773695f']

In [75]: stop()
Stopping...
+-----------+------------+-------------+-------------+-----------------------+------------+------------+------------+------------+------------+
generator dscan ['51200b'] (scan num: 65493)

In [76]: RE(dscan(sz,-.025,0.025,10))
Exception ignored in: <generator object wrapped at 0x7fda18321cf0>
Traceback (most recent call last):
  File "/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/plans.py", line 70, in wrapped
    yield from g
  File "/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/plans.py", line 1323, in reset_positions_wrapper
    reset()))
RuntimeError: generator ignored GeneratorExit
Transient Scan ID: 65494
Persistent Unique Scan ID: 'e53786b2-6413-4a6e-be67-001300913531'
+-----------+------------+-------------+-------------+-----------------------+------------+------------+------------+------------+------------+
|   seq_num |       time | sz_readback | sz_setpoint | dif_beam_stats2_total | mono_tempa | mono_tempb |  grt1_temp |  grt2_temp |    uw_temp |
+-----------+------------+-------------+-------------+-----------------------+------------+------------+------------+------------+------------+
|         1 | 22:37:29.9 |       0.912 |       0.912 |              12776056 |    302.744 |    302.745 |       31.6 |       28.7 |      84.91 |
|         2 | 22:37:35.1 |       0.917 |       0.917 |              11649033 |    302.745 |    302.746 |       31.5 |       28.9 |      84.88 |
|         3 | 22:37:40.5 |       0.922 |       0.922 |              11599523 |    302.746 |    302.750 |       31.6 |       28.7 |      84.91 |
|         4 | 22:37:45.9 |       0.927 |       0.927 |              11594157 |    302.748 |    302.751 |       31.6 |       28.7 |      84.90 |
|         5 | 22:37:51.2 |       0.932 |       0.932 |              11593268 |    302.747 |    302.747 |       31.6 |       28.8 |      84.88 |
|         6 | 22:37:56.6 |       0.937 |       0.937 |              11593575 |    302.749 |    302.749 |       31.6 |       28.7 |      84.87 |
|         7 | 22:38:01.9 |       0.942 |       0.942 |              11595924 |    302.749 |    302.747 |       31.6 |       28.7 |      84.88 |
|         8 | 22:38:07.2 |       0.947 |       0.947 |              11605278 |    302.750 |    302.748 |       31.6 |       28.7 |      84.88 |
|         9 | 22:38:12.3 |       0.952 |       0.952 |              11588984 |    302.751 |    302.750 |       31.5 |       28.9 |      84.91 |
|        10 | 22:38:17.6 |       0.957 |       0.957 |              11599084 |    302.752 |    302.749 |       31.6 |       28.7 |      84.91 |
|        11 | 22:38:22.8 |       0.962 |       0.962 |              11583689 |    302.750 |    302.750 |       31.6 |       28.7 |      84.90 |
+-----------+------------+-------------+-------------+-----------------------+------------+------------+------------+------------+------------+
generator dscan ['e53786'] (scan num: 65494)
Out[76]: ['e53786b2-6413-4a6e-be67-001300913531']

In [77]: RE(dscan(sz,-.025,0.025,10))
Transient Scan ID: 65495
Persistent Unique Scan ID: '9cc33d0d-fd79-4e35-aad1-be6908d59846'
+-----------+------------+-------------+-------------+-----------------------+------------+------------+------------+------------+------------+
|   seq_num |       time | sz_readback | sz_setpoint | dif_beam_stats2_total | mono_tempa | mono_tempb |  grt1_temp |  grt2_temp |    uw_temp |
+-----------+------------+-------------+-------------+-----------------------+------------+------------+------------+------------+------------+
|         1 | 22:39:06.3 |       0.889 |       0.889 |              13104861 |    302.748 |    302.744 |       31.6 |       28.8 |      84.90 |
|         2 | 22:39:12.0 |       0.894 |       0.894 |              13120115 |    302.747 |    302.751 |       31.6 |       28.7 |      84.89 |
|         3 | 22:39:17.5 |       0.899 |       0.899 |              13115575 |    302.748 |    302.750 |       31.6 |       28.7 |      84.90 |
|         4 | 22:39:22.8 |       0.904 |       0.904 |              13074414 |    302.748 |    302.749 |       31.5 |       28.7 |      84.92 |
|         5 | 22:39:28.0 |       0.909 |       0.909 |              13069651 |    302.746 |    302.742 |       31.6 |       28.8 |      84.92 |
|         6 | 22:39:33.4 |       0.914 |       0.914 |              12327170 |    302.744 |    302.745 |       31.5 |       28.7 |      84.92 |
|         7 | 22:39:39.0 |       0.919 |       0.919 |              11620880 |    302.747 |    302.744 |       31.6 |       28.8 |      84.93 |
|         8 | 22:39:44.3 |       0.924 |       0.924 |              11596485 |    302.750 |    302.744 |       31.5 |       28.7 |      84.95 |
|         9 | 22:39:49.5 |       0.929 |       0.929 |              11597900 |    302.749 |    302.746 |       31.6 |       28.9 |      84.97 |
|        10 | 22:39:55.0 |       0.934 |       0.934 |              11585970 |    302.749 |    302.754 |       31.6 |       28.7 |      84.97 |
|        11 | 22:40:00.4 |       0.939 |       0.939 |              11603759 |    302.748 |    302.756 |       31.6 |       28.9 |      84.97 |
+-----------+------------+-------------+-------------+-----------------------+------------+------------+------------+------------+------------+
generator dscan ['9cc33d'] (scan num: 65495)
Out[77]: ['9cc33d0d-fd79-4e35-aad1-be6908d59846']

```

``````
^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
stop()
|        10 | 22:45:00.3 |    -0.2500 |             -0.2500 |              13103774 |    302.749 |    302.747 |       31.6 |       28.7 |      84.98 |
Pausing...
Out[79]: ['e3e7fcd6-8661-4fe2-8265-18a8a577e81a']

````In [80]: stop()
Stopping...
+-----------+------------+------------+---------------------+-----------------------+------------+------------+------------+------------+------------+
generator dscan ['e3e7fc'] (scan num: 65497)

In [81]: RE(dscan(theta,-2,2,20))
Exception ignored in: <generator object wrapped at 0x7fd9f824de58>
Traceback (most recent call last):
  File "/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/plans.py", line 70, in wrapped
    yield from g
  File "/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/plans.py", line 1323, in reset_positions_wrapper
    reset()))
RuntimeError: generator ignored GeneratorExit
Transient Scan ID: 65498
Persistent Unique Scan ID: '28c93e5f-a26d-4e54-a5b7-6844b672d9ce'
+-----------+------------+------------+---------------------+-----------------------+------------+------------+------------+------------+------------+
|   seq_num |       time |      theta | theta_user_setpoint | dif_beam_stats2_total | mono_tempa | mono_tempb |  grt1_temp |  grt2_temp |    uw_temp |
+-----------+------------+------------+---------------------+-----------------------+------------+------------+------------+------------+------------+
|         1 | 22:47:56.3 |    -2.7000 |             -2.7000 |              11589652 |    302.749 |    302.749 |       31.6 |       28.7 |      85.00 |
|         2 | 22:48:03.1 |    -2.5000 |             -2.5000 |              11600430 |    302.749 |    302.750 |       31.6 |       28.7 |      85.01 |
|         3 | 22:48:09.8 |    -2.3000 |             -2.3000 |              11577603 |    302.749 |    302.747 |       31.6 |       28.8 |      85.00 |
|         4 | 22:48:16.4 |    -2.1000 |             -2.1000 |              11593270 |    302.750 |    302.746 |       31.5 |       28.7 |      84.99 |
|         5 | 22:48:23.2 |    -1.9000 |             -1.9000 |              11640485 |    302.749 |    302.751 |       31.6 |       28.7 |      85.02 |
|         6 | 22:48:30.0 |    -1.7000 |             -1.7000 |              12973864 |    302.749 |    302.749 |       31.6 |       28.7 |      85.02 |
|         7 | 22:48:36.6 |    -1.5000 |             -1.5000 |              13079304 |    302.750 |    302.747 |       31.5 |       28.7 |      85.00 |
``````

**Comment by tacaswell** [comment]
Thanks.  We are aware of this one and have a guess at how to fix it.  Just to check, it is not messing with the _next_ scan?  Just spamming the screen a bit?

attn @klauer

**Comment by ambarb** [comment]
This is correct.  The scan is okay.

**Comment by tacaswell** [comment]
A MWE is

``` python
import bluesky as bs
import bluesky.plans as bp
from bluesky.examples import motor, det

RE = bs.RunEngine({})
RE.msg_hook = print

@bp.reset_positions_decorator
@bp.relative_set_decorator
def simple_plan(motor):
    for j in range(15):
        yield bs.Msg('set', motor, j)
    yield bs.Msg('pause')
    for j in range(15):
        yield bs.Msg('set', motor, -j)

RE(simple_plan(motor))
RE.stop()
RE(simple_plan(motor))
```

@ambarb Are you sure that the scans are working properly?  It looks like if you stop or abort a delta scan the motors do not get reset to their initial position.

**Comment by ambarb** [comment]
Oh. Yes. That is correct. I thought you guys mentioned the data.

Thomas A Caswell notifications@github.com wrote:

A MWE is

import bluesky as bs
import bluesky.plans as bp
from bluesky.examples import motor, det

RE = bs.RunEngine({})
RE.msg_hook = print

@bp.reset_positions_decorator
@bp.relative_set_decorator
def simple_plan(motor):
    for j in range(15):
        yield bs.Msg('set', motor, j)
    yield bs.Msg('pause')
    for j in range(15):
        yield bs.Msg('set', motor, -j)

RE(simple_plan(motor))
RE.stop()
RE(simple_plan(motor))

@ambarbhttps://github.com/ambarb Are you sure that the scans are working properly? It looks like if you stop or abort a delta scan the motors do not get reset to their initial position.

**Comment by tacaswell** [comment]
Is it reasonable behavior that on `stop` the motors reset and `abort` they do not?

**Comment by ambarb** [comment]
I will check tomorrow.  We have users that are collecting data.

I thought that `dscan()` was designed to behave like the spec dscan (to always return to initial position regardless of scan completion or ``^C`).  This is the intent, yes?

**Comment by tacaswell** [comment]
That is the intent, but there is a bug and it is not currently doing that (https://github.com/NSLS-II/bluesky/pull/492).  The question is that on 'abort'  (which to me means 'something has gone wrong STOP ALL THE MOTORS AND DONT TOUCH THEM') should it also try to move the motors back.  @danielballan rightly points out that this is mixing saying 'the hardware is borked' with 'this data is junk' so `abort` should return the motors to their original positions.

Maybe we should invent a third way to exit a paused RunEngine (like 'halt', 'panic', 'kill' ?) that would give you a way to return the RE to an idle state without changing the hardware state.

**Comment by danielballan** [comment]
Right. Very much looking for feedback from beamline staff on that last bit.

**Comment by ambarb** [comment]
I am not sure how you want to implement, but ideally, the dscan should always return to the origin.  After stop() or abort(),  ^C is issued during the move back to the original point, then the motor should stop.  ^C during motor move outside a scan should alway result in the motors stopping. I believe @stuwilkins agrees. @cmazzoli please chime in either way.

**Comment by tacaswell** [comment]
Closing as NSLS-II/bluesky#492 is merged.

Created https://github.com/NSLS-II/ophyd/issues/341 to track the make-safe-on-ctrl-c

created https://github.com/NSLS-II/bluesky/issues/502 to track the issue adding a 'halt' method to RE.
