### ISSUE TITLE
Ctrl+C behaviour

### ISSUE THREAD

**Issue by cmazzoli** [NSLS-II/Bug-Reports#128]
Maybe I simply remember it wrongly. If so apologies.
In the past we discussed about how to stop a measurement, which I believe generated the multiple Ctrl+C behaviour currently implemented.
We still get problems with scripts, motor motions (also via HKL calcs), detector counting (sometimes keeping counting) when pressing (one or more) time the key combination. For example:

```

|       127 | 11:31:01.5 |    72.0000 |             72.0000 |           1365106 |         109934284 |          77012195 |          39928449 |    302.772 |    302.755 |       33.3 |       28.8 |      90.20 |
|       128 | 11:31:17.5 |    71.5000 |             71.5000 |           1464403 |         115451570 |          82354251 |          42525927 |    302.773 |    302.748 |       33.4 |       28.9 |      88.08 |
|       129 | 11:31:33.6 |    71.0000 |             71.0000 |           1553105 |         122522550 |          88431463 |          45705911 |    302.809 |    302.746 |       33.4 |       28.9 |      85.50 |
|       130 | 11:31:49.5 |    70.5000 |             70.5000 |           -580641 |          -8838139 |         -31941176 |         -13613515 |    302.792 |    302.747 |       33.0 |       28.8 |      82.85 |
^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
^C^CAborting....
^C+-----------+------------+------------+---------------------+-------------------+-------------------+-------------------+-------------------+------------+------------+------------+------------+------------+
generator ascan ['383d12'] (scan num: 66658)
Current fCCD config: 60.0 images @ 0.50 Hz = 120.0 s

   theta              delta              gamma              

    100.0000 deg       142.0000 deg       10.0002 deg        

Transient Scan ID: 66659
Persistent Unique Scan ID: '12774f25-778f-4b56-b136-c3a7aadd991a'
^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
^C^CAborting....
^Cgenerator ct ['12774f'] (scan num: 66659)

Starting procedure to acquire camera gains at 0.5Hz
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
/home/xf23id1/Beamline/Commissioning/2016_07/2016_07_09_morning.py in <module>()
     54 #TempEquil(templimit=0.1)
     55 #sleep(600)
---> 56 one_T()
     57 
     58 # T = 280K

/home/xf23id1/Beamline/Commissioning/2016_07/2016_07_09_morning.py in one_T()
      7     ## on the main edge
      8     one_meas(776.5)
----> 9     service_meas()
     10     ## on the pre-edge
     11     one_meas(773.5)

/home/xf23id1/Beamline/Commissioning/2016_07/2016_07_09_morning.py in service_meas()
     35     # darks
     36     olog('All darks #{}+0:2 @ {:.1f}Hz'.format((db[-1].get('start').get('scan_id'))+1, 1./fccd.acquire_time.get()))
---> 37     ct_all_dark()
     38 
     39 

/home/xf23id1/Beamline/Commissioning/2016_07/2016_07_09_morning.py in ct_all_dark()
     93     print('\nStarting procedure to acquire camera gains at {}Hz'.format(1/fccd.acquire_time.get()))
     94     caput('XF:23ID1-OP{FBck}Sts:FB-Sel',0) #maintain finepitch
---> 95     sleep(2)
     96     # Save current settings
     97     shutter_open = shchk()

KeyboardInterrupt: 

In [314]: Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/IPython/lib/inputhookqt4.py", line 90, in inputhook_qt4
    try:
KeyboardInterrupt

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True


KeyboardInterrupt

In [314]: 

```

I had to Crtl+C a number of times trying to avoid other commands to be executed (without success...) and finally getting the prompt back.
Unfortunately, this might result in dramatic perturbations of the measurement status.
Is the equivalent of a simple, robust and effective "STOP everything NOW and listen to me" command available?

**Comment by tacaswell** [comment]
This is the reason that we keep telling you to write plans (that get handed to the RE on one shot) rather than writing functions that call the RE.  

If you insist on making multiple calls to the RE in a function, do so with `raise_if_interrupted=True` as a kwarg.

**Comment by danielballan** [comment]
@cmazzoli When I get back from scipy, let's sit down and convert some of your scripts to proper plans. There are others who are also interested in this. We'll do a little workshop with a small group.

**Comment by danielballan** [comment]
A workshop covering plans is tentatively planned for a week from this coming Wednesday. Closing this issue.
