### ISSUE TITLE
Replay not responsive

### ISSUE THREAD

**Issue by afluerasu** [NSLS-II/Bug-Reports#14]
```
Traceback (most recent call last):
  File "/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/enaml/qt/qt_abstract_button.py", line 76, in on_clicked
    self.declaration.clicked(checked)
  File "/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/enaml/core/declarative_meta.py", line 68, in declarative_change_handler
    engine.write(owner, change['name'], change)
  File "/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/enaml/core/expression_engine.py", line 210, in write
    pair.writer(owner, name, change)
  File "/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/enaml/core/standard_handlers.py", line 82, in __call__
    call_func(func, (), {}, scope)
  File "/home/xf11id/Repos/replay/replay/search/view.enaml", line 67, in <module>
    search_model.header = loop_item
  File "/home/xf11id/Repos/replay/replay/search/model.py", line 83, in new_run_header
    self.header = changed['value']
  File "/home/xf11id/Repos/replay/replay/search/model.py", line 108, in header_changed
    self.header_keys = header_keys
  File "/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/enaml/core/standard_tracer.py", line 55, in __call__
    engine.update(owner, self.name)
  File "/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/enaml/core/expression_engine.py", line 241, in update
    setattr(owner, name, pair.reader(owner, name))
  File "/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/enaml/core/standard_handlers.py", line 101, in __call__
    return call_func(func, (tr,), {}, scope)
  File "/home/xf11id/Repos/replay/replay/search/view.enaml", line 142, in <module>
    objects << gen_objects(display_header_model.header_keys)
  File "/home/xf11id/Repos/replay/replay/search/view.enaml", line 154, in gen_objects
    objs.append(Label(text = key[1]))
  File "/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/enaml/core/object.py", line 98, in __init__
    super(Object, self).__init__(**kwargs)
TypeError: The 'text' member on the 'Label' object must be of type 'unicode'. Got object of type 'NoneType' instead.
```

**Comment by ericdill** [comment]
@afluerasu is this still a problem?
