### ISSUE TITLE
Scan pause with 'l' typed on command line instead of LivePlot

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/Bug-Reports#145]
I realize that the answer may be don't do this, but I am sure that I have done this before and didn't have a problem.  Lookse like my data wasn't affect but I was not moving motors....just a time scan.

At end of lines below, the lines and lines of repeat on and on until I think I hit ^C.  then data collection started and LivePlot continued to work.  Using newest version of matplotlib. 

```
|        42 | 21:09:04.8 |       1848 |
|        43 | 21:09:05.2 |       1813 |
|        44 | 21:09:05.7 |       1798 |
|        45 | 21:09:06.2 |       1788 |
|        46 | 21:09:06.7 |       1773 |
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py in keyPressEvent(self, event)
    312         if key is None:
    313             return
--> 314         FigureCanvasBase.key_press_event(self, key, guiEvent=event)
    315         if DEBUG:
    316             print('key press', key)

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backend_bases.py in key_press_event(self, key, guiEvent)
   1844         event = KeyEvent(
   1845             s, self, key, self._lastx, self._lasty, guiEvent=guiEvent)
-> 1846         self.callbacks.process(s, event)
   1847 
   1848     def key_release_event(self, key, guiEvent=None):

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/cbook.py in process(self, s, *args, **kwargs)
    548             for cid, proxy in list(six.iteritems(self.callbacks[s])):
    549                 try:
--> 550                     proxy(*args, **kwargs)
    551                 except ReferenceError:
    552                     self._remove_proxy(proxy)

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/cbook.py in __call__(self, *args, **kwargs)
    415             mtd = self.func
    416         # invoke the callable and return the result
--> 417         return mtd(*args, **kwargs)
    418 
    419     def __eq__(self, other):

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backend_bases.py in key_press(self, event)
   2649         """
   2650         if rcParams['toolbar'] != 'toolmanager':
-> 2651             key_press_handler(event, self.canvas, self.canvas.toolbar)
   2652 
   2653     def show_popup(self, msg):

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backend_bases.py in key_press_handler(event, canvas, toolbar)
   2553                 warnings.warn(str(exc))
   2554                 ax.set_yscale('linear')
-> 2555             ax.figure.canvas.draw()
   2556     # toggle scaling of x-axes between 'log and 'linear' (default key 'k')
   2557     elif event.key in toggle_xscale_keys:

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py in draw(self)
    160         # The Agg draw is done here; delaying causes problems with code that
    161         # uses the result of the draw() to update plot elements.
--> 162         FigureCanvasAgg.draw(self)
    163         self.update()
    164 

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    461 
    462         try:
--> 463             self.figure.draw(self.renderer)
    464         finally:
    465             RendererAgg.lock.release()

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     61     def draw_wrapper(artist, renderer, *args, **kwargs):
     62         before(artist, renderer)
---> 63         draw(artist, renderer, *args, **kwargs)
     64         after(artist, renderer)
     65 

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/figure.py in draw(self, renderer)
   1127 
   1128         mimage._draw_list_compositing_images(
-> 1129             renderer, self, dsu, self.suppressComposite)
   1130 
   1131         renderer.close_group('figure')

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, dsu, suppress_composite)
    137     if not_composite or not has_images:
    138         for zorder, a in dsu:
--> 139             a.draw(renderer)
    140     else:
    141         # Composite any adjacent images together

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     61     def draw_wrapper(artist, renderer, *args, **kwargs):
     62         before(artist, renderer)
---> 63         draw(artist, renderer, *args, **kwargs)
     64         after(artist, renderer)
     65 

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2382             renderer.stop_rasterizing()
   2383 
-> 2384         mimage._draw_list_compositing_images(renderer, self, dsu)
   2385 
   2386         renderer.close_group('axes')

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, dsu, suppress_composite)
    137     if not_composite or not has_images:
    138         for zorder, a in dsu:
--> 139             a.draw(renderer)
    140     else:
    141         # Composite any adjacent images together

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     61     def draw_wrapper(artist, renderer, *args, **kwargs):
     62         before(artist, renderer)
---> 63         draw(artist, renderer, *args, **kwargs)
     64         after(artist, renderer)
     65 

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py in draw(self, renderer, *args, **kwargs)
   1124         renderer.open_group(__name__)
   1125 
-> 1126         ticks_to_draw = self._update_ticks(renderer)
   1127         ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
   1128                                                                 renderer)

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py in _update_ticks(self, renderer)
    957 
    958         interval = self.get_view_interval()
--> 959         tick_tups = [t for t in self.iter_ticks()]
    960         if self._smart_bounds:
    961             # handle inverted limits

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py in <listcomp>(.0)
    957 
    958         interval = self.get_view_interval()
--> 959         tick_tups = [t for t in self.iter_ticks()]
    960         if self._smart_bounds:
    961             # handle inverted limits

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py in iter_ticks(self)
    902         majorLocs = self.major.locator()
    903         majorTicks = self.get_major_ticks(len(majorLocs))
--> 904         self.major.formatter.set_locs(majorLocs)
    905         majorLabels = [self.major.formatter(val, i)
    906                        for i, val in enumerate(majorLocs)]

/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/ticker.py in set_locs(self, locs)
    837                 numdec += math.log(vmax / vmin) / math.log(b)
    838         else:
--> 839             vmin = math.log(vmin) / math.log(b)
    840             vmax = math.log(vmax) / math.log(b)
    841             numdec = abs(vmax - vmin)

ValueError: math domain error
Traceback (most recent call last):
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 183, in __draw_idle_agg
    FigureCanvasAgg.draw(self)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 463, in draw
    self.figure.draw(self.renderer)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/figure.py", line 1129, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2384, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py", line 1126, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py", line 959, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py", line 959, in <listcomp>
    tick_tups = [t for t in self.iter_ticks()]
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py", line 904, in iter_ticks
    self.major.formatter.set_locs(majorLocs)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/ticker.py", line 839, in set_locs
    vmin = math.log(vmin) / math.log(b)
ValueError: math domain error
Traceback (most recent call last):
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 183, in __draw_idle_agg
    FigureCanvasAgg.draw(self)
```

**Comment by ambarb** [comment]
```
In [31]: matplotlib.__version__
Out[31]: '2.0.0b4'
```

**Comment by tacaswell** [comment]
I think that this is fixed in the development branch.

The problem is that there is a < 0 value is your range which the log scaling is choking :/
