### ISSUE TITLE
Potential matplotlib issue 

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/Bug-Reports#146]

**Comment by ambarb** [comment]
```
In [31]: matplotlib.__version__
Out[31]: '2.0.0b4'
```

multiple scans in a LivePlot and tried to scale with `l`

```
In [30]: Traceback (most recent call last):
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 314, in keyPressEvent
    FigureCanvasBase.key_press_event(self, key, guiEvent=event)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 1846, in key_press_event
    self.callbacks.process(s, event)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/cbook.py", line 550, in process
    proxy(*args, **kwargs)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/cbook.py", line 417, in __call__
    return mtd(*args, **kwargs)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2651, in key_press
    key_press_handler(event, self.canvas, self.canvas.toolbar)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2555, in key_press_handler
    ax.figure.canvas.draw()
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 162, in draw
    FigureCanvasAgg.draw(self)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 463, in draw
    self.figure.draw(self.renderer)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/figure.py", line 1129, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2384, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py", line 1126, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py", line 959, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py", line 959, in <listcomp>
    tick_tups = [t for t in self.iter_ticks()]
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/axis.py", line 904, in iter_ticks
    self.major.formatter.set_locs(majorLocs)
  File "/home/xf23id1/conda_envs/collection/lib/python3.5/site-packages/matplotlib/ticker.py", line 839, in set_locs
    vmin = math.log(vmin) / math.log(b)
ValueError: math domain error

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```
