### ISSUE TITLE
inconsistency in scan database prevents replay from starting

### ISSUE THREAD

**Issue by afluerasu** [NSLS-II/Bug-Reports#25]
Some scan record contain errors related to non-existent dark files. When such a scan exists in the database, replay does not start

xf11id@xf11id-ws1:~$ ./replay
discarding /nfs/xf11id/mc/bin from PATH
prepending /nfs/xf11id/mc/envs/ophyd/bin to PATH
/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py:210: MatplotlibDeprecationWarning: This class has been deprecated in 1.4 as it has no additional functionality over `NavigationToolbar2QT`.  Please change your code to use `NavigationToolbar2QT` instead
  mplDeprecation)
/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/enaml/qt/docking/dock_manager.py:184: DockLayoutWarning: child SplitLayout has same orientation as parent
  DockLayoutValidator(available)(layout)
Traceback (most recent call last):
  File "/nfs/xf11id/mc/envs/ophyd/bin/replay", line 9, in <module>
    load_entry_point('replay==0.0.0.dev0', 'console_scripts', 'replay')()
  File "/home/xf11id/Repos/replay/replay/replay.py", line 176, in main
    ui.muxer_model.header = db[-1]
  File "/home/xf11id/Repos/replay/replay/muxer/model.py", line 209, in _run_header_changed
    self.get_new_data()
  File "/home/xf11id/Repos/replay/replay/muxer/model.py", line 226, in get_new_data
    self.event_queue.update()
  File "/home/xf11id/Repos/dataportal/dataportal/broker/simple_broker.py", line 251, in update
    [fill_event(event) for event in new_events]
  File "/home/xf11id/Repos/dataportal/dataportal/broker/simple_broker.py", line 311, in fill_event
    event.data[data_key] = retrieve(value)
  File "build/bdist.linux-x86_64/egg/filestore/commands.py", line 21, in inner
    from warnings import warnpy3k
  File "build/bdist.linux-x86_64/egg/filestore/commands.py", line 120, in retrieve

  File "build/bdist.linux-x86_64/egg/filestore/retrieve.py", line 223, in get_data
  File "build/bdist.linux-x86_64/egg/filestore/handlers.py", line 66, in **call**
filestore.handlers.IntegrityError: Seeking Frame 52 out of 26 frames.
xf11id@xf11id-ws1:~$

**Comment by ericdill** [comment]
Replay crashing is definitely a bug.  That is fixed by NSLS-II/replay#27.

The exception raised here by filestore is the same one that was seen earlier by @yugangzhang in #23.  I am both unsure what is causing this problem and unaware of a way to fix this.  Perhaps @tacaswell, @dchabot or @danielballan have some ideas?

**Comment by ericdill** [comment]
Next time that this happens to you, can you check and see if `xray_cam_img` appears in your scan object's detectors **twice**?

**Comment by danielballan** [comment]
Replay is enjoying retirement. It wanted more time to spend with its family. :- ) So I will close this.

For live data we have bluesky and for reviewing scans we have notebooks and the experimental new package, "album." All of this is deployed at CHX. Will sit down to demo and teach next week.
