### ISSUE TITLE
Got error when running fitting GUI under ophyd

### ISSUE THREAD

**Issue by licode** [NSLS-II/Bug-Reports#28]
```
(li_ophyd_new)xf03id@xf03idc-ws2:~/code_lili/git_source/PyXRF$ pyxrf
/home/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/pcaspy-0.5.1-py2.7-linux-x86_64.egg/pcaspy/../../../../libreadline.so.6: undefined symbol: PC
2015-08-12 14:22:51,341 [ophyd_session:WARNING] Instantiating SessionManager outside of IPython
Traceback (most recent call last):
  File "/home/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/pyepics-3.2.4rc2-py2.7.egg/epics/ca.py", line 207, in initialize_libca
    libca = load_dll(dllname)
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/xf03id/mc/envs/li_ophyd_new/bin/../lib/libreadline.so.6: undefined symbol: PC
Traceback (most recent call last):
  File "/nfs/xf03id/mc/envs/li_ophyd_new/bin/pyxrf", line 9, in <module>
    load_entry_point('pyxrf==0.0.0.post0', 'console_scripts', 'pyxrf')()
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 2355, in load
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/home/xf03id/code_lili/git_source/PyXRF/pyxrf/gui.py", line 44, in <module>
    from pyxrf.model.fileio import FileIOModel
  File "/home/xf03id/code_lili/git_source/PyXRF/pyxrf/model/fileio.py", line 58, in <module>
    import hxntools.detectors
  File "/home/xf03id/Repos/hxntools/hxntools/detectors/__init__.py", line 6, in <module>
    from .beamstatus import (BeamStatusDetector, )
  File "/home/xf03id/Repos/hxntools/hxntools/detectors/beamstatus.py", line 11, in <module>
    name='sr_shutter_status')
  File "/home/xf03id/Repos/ophyd/ophyd/controls/signal.py", line 210, in __init__
    **kwargs)
  File "/home/xf03id/Repos/ophyd/ophyd/controls/signal.py", line 48, in __init__
    OphydObject.__init__(self, **kwargs)
  File "/home/xf03id/Repos/ophyd/ophyd/controls/ophydobj.py", line 51, in __init__
    self._register()
  File "/home/xf03id/Repos/ophyd/ophyd/controls/ophydobj.py", line 172, in _register
    register_object(self)
  File "/home/xf03id/Repos/ophyd/ophyd/session/__init__.py", line 37, in register_object
    ses = get_session_manager()
  File "/home/xf03id/Repos/ophyd/ophyd/session/__init__.py", line 16, in get_session_manager
    SessionManager(logging.getLogger(OPHYD_LOGGER), None)
  File "/home/xf03id/Repos/ophyd/ophyd/session/sessionmgr.py", line 63, in __init__
    self._setup_epics()
  File "/home/xf03id/Repos/ophyd/ophyd/session/sessionmgr.py", line 278, in _setup_epics
    epics.ca.use_initial_context()
  File "/home/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/pyepics-3.2.4rc2-py2.7.egg/epics/ca.py", line 343, in wrapper
    initialize_libca()
  File "/home/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/pyepics-3.2.4rc2-py2.7.egg/epics/ca.py", line 209, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: /home/xf03id/mc/envs/li_ophyd_new/bin/../lib/libreadline.so.6: undefined symbol: PC
(li_ophyd_new)xf03id@xf03idc-ws2:~/code_lili/git_source/PyXRF$ pyxrf
/home/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/pcaspy-0.5.1-py2.7-linux-x86_64.egg/pcaspy/../../../../libreadline.so.6: undefined symbol: PC
2015-08-12 14:23:05,411 [ophyd_session:WARNING] Instantiating SessionManager outside of IPython
Traceback (most recent call last):
  File "/home/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/pyepics-3.2.4rc2-py2.7.egg/epics/ca.py", line 207, in initialize_libca
    libca = load_dll(dllname)
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/xf03id/mc/envs/li_ophyd_new/bin/../lib/libreadline.so.6: undefined symbol: PC
Traceback (most recent call last):
  File "/nfs/xf03id/mc/envs/li_ophyd_new/bin/pyxrf", line 9, in <module>
    load_entry_point('pyxrf==0.0.0.post0', 'console_scripts', 'pyxrf')()
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 2355, in load
  File "/nfs/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/home/xf03id/code_lili/git_source/PyXRF/pyxrf/gui.py", line 44, in <module>
    from pyxrf.model.fileio import FileIOModel
  File "/home/xf03id/code_lili/git_source/PyXRF/pyxrf/model/fileio.py", line 58, in <module>
    import hxntools.detectors
  File "/home/xf03id/Repos/hxntools/hxntools/detectors/__init__.py", line 6, in <module>
    from .beamstatus import (BeamStatusDetector, )
  File "/home/xf03id/Repos/hxntools/hxntools/detectors/beamstatus.py", line 11, in <module>
    name='sr_shutter_status')
  File "/home/xf03id/Repos/ophyd/ophyd/controls/signal.py", line 210, in __init__
    **kwargs)
  File "/home/xf03id/Repos/ophyd/ophyd/controls/signal.py", line 48, in __init__
    OphydObject.__init__(self, **kwargs)
  File "/home/xf03id/Repos/ophyd/ophyd/controls/ophydobj.py", line 51, in __init__
    self._register()
  File "/home/xf03id/Repos/ophyd/ophyd/controls/ophydobj.py", line 172, in _register
    register_object(self)
  File "/home/xf03id/Repos/ophyd/ophyd/session/__init__.py", line 37, in register_object
    ses = get_session_manager()
  File "/home/xf03id/Repos/ophyd/ophyd/session/__init__.py", line 16, in get_session_manager
    SessionManager(logging.getLogger(OPHYD_LOGGER), None)
  File "/home/xf03id/Repos/ophyd/ophyd/session/sessionmgr.py", line 63, in __init__
    self._setup_epics()
  File "/home/xf03id/Repos/ophyd/ophyd/session/sessionmgr.py", line 278, in _setup_epics
    epics.ca.use_initial_context()
  File "/home/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/pyepics-3.2.4rc2-py2.7.egg/epics/ca.py", line 343, in wrapper
    initialize_libca()
  File "/home/xf03id/mc/envs/li_ophyd_new/lib/python2.7/site-packages/pyepics-3.2.4rc2-py2.7.egg/epics/ca.py", line 209, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: /home/xf03id/mc/envs/li_ophyd_new/bin/../lib/libreadline.so.6: undefined symbol: PC
```

**Comment by tacaswell** [comment]
You are using the wrong version of read line.

**Comment by ericdill** [comment]
Conda install -c hxn readline -f

**Comment by ericdill** [comment]
Sort of related... Can we just install Ubuntu 14.04 LTS on these machines
yet?? Cc @danielballan because you seem to have a great relationship with
the sysadmins!

**Comment by danielballan** [comment]
Haha, yeah I agree. We'll see. Even IBM is making the switch to Ubuntu.
