### ISSUE TITLE
Can't used databroker in a remote computer

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#37]
I log in (CHX) xf11id-ws1 by my computer,  I had a problem to load databorker under "analysis" environment. Eric help me to create a new environment "test"  by  " conda create -n test analysis ". I got a same wrong message:

``` python
  In [1]: %pdb
Automatic pdb calling has been turned ON

In [2]: from databroker import DataBroker as db, get_events, get_images, get_table

In [3]: ---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/terminal/interactiveshell.py in raw_input(self, prompt)
    526 
    527         try:
--> 528             line = py3compat.cast_unicode_py2(self.raw_input_original(prompt))
    529         except ValueError:
    530             warn("\n********\nYou or a %run:ed script called sys.stdin.close()"

OSError: [Errno 9] Bad file descriptor
> /home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/terminal/interactiveshell.py(533)raw_input()
    532             self.ask_exit()
--> 533             return ""
    534 

ipdb> Traceback (most recent call last):
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/terminal/interactiveshell.py", line 459, in interact
    line = self.raw_input(prompt)
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/terminal/interactiveshell.py", line 528, in raw_input
    line = py3compat.cast_unicode_py2(self.raw_input_original(prompt))
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuzhang/.conda/envs/test/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 353, in start
    self.shell.mainloop()
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/terminal/interactiveshell.py", line 381, in mainloop
    self.interact(display_banner=display_banner)
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/terminal/interactiveshell.py", line 491, in interact
    self.showtraceback()
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 1885, in showtraceback
    self.debugger(force=True)
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 1051, in debugger
    pm()
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 1048, in <lambda>
    pm = lambda : self.InteractiveTB.debugger(force=True)
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/core/ultratb.py", line 1077, in debugger
    self.pdb.interaction(self.tb.tb_frame, self.tb)
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/site-packages/IPython/core/debugger.py", line 279, in interaction
    OldPdb.interaction(self, frame, traceback)
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/pdb.py", line 346, in interaction
    self._cmdloop()
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/pdb.py", line 319, in _cmdloop
    self.cmdloop()
  File "/home/yuzhang/.conda/envs/test/lib/python3.4/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
OSError: [Errno 9] Bad file descriptor

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by danielballan** [comment]
There is something wrong with your home directory. This is not a databroker
issue. Ask Robert Petkus.

**Comment by danielballan** [comment]
Closing, reopen if this turns out to be a problem on our side.

**Comment by yugangzhang** [comment]
Very painful because I can't use my computer to do the job  for xf11id!

**Comment by danielballan** [comment]
Understood. Use jupyterhub in the meantime, and pester the sysadmins on this. I hear you, but we can't help you.

**Comment by ericdill** [comment]
@yugangzhang why don't you just log in with your account and then `su xf11id`?

**Comment by yugangzhang** [comment]
I tried but I always have this problem:

X11 connection rejected because of wrong authentication.
 : cannot connect to X server localhost:10.0
