### ISSUE TITLE
Replay problem

### ISSUE THREAD

**Issue by cmazzoli** [NSLS-II/Bug-Reports#5]
This is what was shown on xf23id-ws3 once trying to start replay...

```
[xf23id1@xf23id-ws3 ~]$ source activate ophyd
discarding /home/xf23id1/anaconda/bin from PATH
prepending /home/xf23id1/anaconda/envs/ophyd/bin to PATH
(ophyd)[xf23id1@xf23id-ws3 ~]$ replay
/home/xf23id1/anaconda/envs/ophyd/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py:210: MatplotlibDeprecationWarning: This class has been deprecated in 1.4 as it has no additional functionality over `NavigationToolbar2QT`.  Please change your code to use `NavigationToolbar2QT` instead
  mplDeprecation)
/home/xf23id1/anaconda/envs/ophyd/lib/python2.7/site-packages/enaml/qt/docking/dock_manager.py:184: DockLayoutWarning: child SplitLayout has same orientation as parent
  DockLayoutValidator(available)(layout)
Traceback (most recent call last):
  File "/home/xf23id1/anaconda/envs/ophyd/bin/replay", line 6, in <module>
    sys.exit(main())
  File "/home/xf23id1/anaconda/envs/ophyd/lib/python2.7/site-packages/dataportal/replay/replay.py", line 161, in main
    ui.muxer_model.header = db[-1]
  File "/home/xf23id1/anaconda/envs/ophyd/lib/python2.7/site-packages/dataportal/replay/muxer/model.py", line 209, in _run_header_changed
    self.get_new_data()
  File "/home/xf23id1/anaconda/envs/ophyd/lib/python2.7/site-packages/dataportal/replay/muxer/model.py", line 226, in get_new_data
    self.event_queue.update()
  File "/home/xf23id1/anaconda/envs/ophyd/lib/python2.7/site-packages/dataportal/broker/simple_broker.py", line 267, in update
    [fill_event(event) for event in new_events]
  File "/home/xf23id1/anaconda/envs/ophyd/lib/python2.7/site-packages/dataportal/broker/simple_broker.py", line 327, in fill_event
    event.data[data_key] = retrieve(value)
  File "build/bdist.linux-x86_64/egg/filestore/commands.py", line 21, in inner
    from warnings import warnpy3k
  File "build/bdist.linux-x86_64/egg/filestore/commands.py", line 120, in retrieve

  File "build/bdist.linux-x86_64/egg/filestore/retrieve.py", line 222, in get_data
  File "build/bdist.linux-x86_64/egg/filestore/retrieve.py", line 195, in get_spec_handler
  File "build/bdist.linux-x86_64/egg/filestore/handlers.py", line 143, in __init__
  File "build/bdist.linux-x86_64/egg/filestore/handlers.py", line 113, in __init__
  File "build/bdist.linux-x86_64/egg/filestore/handlers.py", line 86, in open
  File "/home/xf23id1/anaconda/envs/ophyd/lib/python2.7/site-packages/h5py/_hl/files.py", line 231, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/home/xf23id1/anaconda/envs/ophyd/lib/python2.7/site-packages/h5py/_hl/files.py", line 78, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py-2.4.0/h5py/_objects.c:2405)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py-2.4.0/h5py/_objects.c:2362)
  File "h5py/h5f.pyx", line 72, in h5py.h5f.open (-------src-dir-------/h5py-2.4.0/h5py/h5f.c:1738)
IOError: Unable to open file (Unable to open file: name = '/gpfs/xf23id/xf23id1/fccd_data/2015/4/26/4c2d7bb3-a00d-4925-b87b-655870c558e6_000000.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
(ophyd)[xf23id1@xf23id-ws3 ~]$ 

```

**Comment by ericdill** [comment]
Looks like there is a problem with the gpfs on 23id.  I think that @stuwilkins has seen this problem before and knows how to fix this?

**Comment by ericdill** [comment]
Also, the fact that replay refuses to open if it cant find this file is definitely a problem

**Comment by ericdill** [comment]
I will add this to NSLS-II/dataportal#159

**Comment by stuwilkins** [comment]
Hi Eric,

This is not a GPFS problem, rather that the data is not mounted on that workstation. This is a very common occurrence and replay should handle this as it can't display the 2d data anyway! (Currently)

Best wishes,
Stuart

On May 7, 2015, at 14:05, Eric Dill <notifications@github.com<mailto:notifications@github.com>> wrote:

Looks like there is a problem with the gpfs on 23id. I think that @stuwilkinshttps://github.com/stuwilkins has seen this problem before and knows how to fix this?
