### ISSUE TITLE
Internal anaconda server SSL error

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/Bug-Reports#72]
This will be a blocking issue to deploy new packages before the beam comes back up.
cc @danielballan @heroux 

```
$ anaconda upload -u edill `conda build 15.0.0 --python=3.5 --output`
Using binstar api site https://conda.nsls2.bnl.gov/api
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file edill/boltons/15.0.0/linux-64/boltons-15.0.0-py35_0.tar.bz2 ... 
[SSLError] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600) 
Traceback (most recent call last):
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 305, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/edill/miniconda/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/home/edill/miniconda/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/home/edill/miniconda/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 588, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/edill/miniconda/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/home/edill/miniconda/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/edill/miniconda/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/edill/miniconda/lib/python3.4/site-packages/binstar_client/commands/upload.py", line 204, in main
    callback=upload_print_callback(args))
  File "/home/edill/miniconda/lib/python3.4/site-packages/binstar_client/__init__.py", line 422, in upload
    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/edill/miniconda/lib/python3.4/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)


```

**Comment by danielballan** [comment]
Mizuki and Continuum are both aware of this issue, now ongoing for several week. Does anyone have the bandwidth to push on this?

**Comment by heroux** [comment]
Sure, I will look into it.

**Comment by heroux** [comment]
Are you closing it because it's solved or because you are giving up?

**Comment by danielballan** [comment]
@heroux Mizuki found a work-around that is sufficient for now. Unless our requirements change, I think we should wait for Continuum to fix the problem on their end.
